[package]
name    = "ncollide_utils"
version = "0.1.0"
authors = [ "Sébastien Crozet <developer@crozet.re>" ]

[lib]
name = "ncollide_utils"
path = "lib.rs"

[dependencies]
rustc-serialize = "*"
rand = "0.1"
rand_macros = "0.1.4"

[dependencies.nalgebra]
git = "https://github.com/sebcrozet/nalgebra"

[dependencies.ncollide_math]
path = "../ncollide_math"
